# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_pagesLTDyHW.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from qt_core import *


class Ui_MainPages(object):
    def setupUi(self, MainPages):
        if not MainPages.objectName():
            MainPages.setObjectName(u"MainPages")
        MainPages.resize(1106, 591)
        self.main_pages_layout = QVBoxLayout(MainPages)
        self.main_pages_layout.setSpacing(0)
        self.main_pages_layout.setObjectName(u"main_pages_layout")
        self.main_pages_layout.setContentsMargins(5, 5, 5, 5)
        self.pages = QStackedWidget(MainPages)
        self.pages.setObjectName(u"pages")
        self.page_1 = QWidget()
        self.page_1.setObjectName(u"page_1")
        self.page_1.setStyleSheet(u"font-size: 14pt")
        self.page_1_layout = QVBoxLayout(self.page_1)
        self.page_1_layout.setSpacing(5)
        self.page_1_layout.setObjectName(u"page_1_layout")
        self.page_1_layout.setContentsMargins(5, 5, 5, 5)
        self.frame = QFrame(self.page_1)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 10, 621, 531))
        self.frame_2.setFrameShape(QFrame.NoFrame)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.frame_2.setLineWidth(0)
        self.frame_load_images = QFrame(self.frame_2)
        self.frame_load_images.setObjectName(u"frame_load_images")
        self.frame_load_images.setGeometry(QRect(60, 160, 521, 301))
        self.frame_load_images.setFrameShape(QFrame.NoFrame)
        self.frame_load_images.setFrameShadow(QFrame.Raised)

        self.frame_load_images.setEnabled(False)
        self.frame_load_images.setVisible(False)


        self.label_3 = QLabel(self.frame_load_images)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(100, 0, 311, 41))
        self.verticalLayoutWidget = QWidget(self.frame_load_images)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(90, 50, 251, 161))
        self.circular_layout = QVBoxLayout(self.verticalLayoutWidget)
        self.circular_layout.setObjectName(u"circular_layout")
        self.circular_layout.setContentsMargins(0, 0, 0, 0)
        self.label_8 = QLabel(self.frame_load_images)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(90, 210, 311, 41))
        self.horizontalLayoutWidget = QWidget(self.frame_load_images)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(80, 240, 321, 49))
        self.btn_layout_4 = QHBoxLayout(self.horizontalLayoutWidget)
        self.btn_layout_4.setObjectName(u"btn_layout_4")
        self.btn_layout_4.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.frame_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 40, 121, 20))
        self.label_2 = QLabel(self.frame_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 490, 131, 20))
        self.groupBox_1 = QGroupBox(self.frame_2)
        self.groupBox_1.setObjectName(u"groupBox_1")
        self.groupBox_1.setGeometry(QRect(10, 10, 571, 71))
        self.groupBox_1.setStyleSheet(u"")
        self.groupBox_1.setFlat(False)
        self.groupBox_1.setCheckable(False)
        self.groupBox_1.setChecked(False)
        self.groupBox_2 = QGroupBox(self.frame_2)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(0, 99, 620, 60))
        self.layoutWidget = QWidget(self.frame_2)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(190, 30, 372, 49))
        self.btn_layout_1 = QHBoxLayout(self.layoutWidget)
        self.btn_layout_1.setObjectName(u"btn_layout_1")
        self.btn_layout_1.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.btn_layout_1.setContentsMargins(1, 1, 1, 1)
        self.layoutWidget1 = QWidget(self.frame_2)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(150, 490, 363, 30))
        self.btn_layout_3 = QHBoxLayout(self.layoutWidget1)
        self.btn_layout_3.setObjectName(u"btn_layout_3")
        self.btn_layout_3.setContentsMargins(0, 0, 0, 0)
        self.layoutWidget2 = QWidget(self.frame_2)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(10, 110, 596, 40))
        self.btn_layout_2 = QHBoxLayout(self.layoutWidget2)
        self.btn_layout_2.setObjectName(u"btn_layout_2")
        self.btn_layout_2.setContentsMargins(0, 0, 0, 0)
        self.frame_train_model = QFrame(self.frame_2)
        self.frame_train_model.setObjectName(u"frame_train_model")
        self.frame_train_model.setGeometry(QRect(60, 160, 521, 301))
        self.frame_train_model.setFrameShape(QFrame.NoFrame)
        self.frame_train_model.setFrameShadow(QFrame.Raised)


        self.frame_train_model.setEnabled(False)
        self.frame_train_model.setVisible(False)





        self.label_11 = QLabel(self.frame_train_model)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(100, 0, 311, 41))
        self.verticalLayoutWidget_3 = QWidget(self.frame_train_model)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(90, 50, 251, 161))
        self.circular_layout_3 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.circular_layout_3.setObjectName(u"circular_layout_3")
        self.circular_layout_3.setContentsMargins(0, 0, 0, 0)
        self.label_12 = QLabel(self.frame_train_model)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(90, 210, 311, 41))
        self.horizontalLayoutWidget_3 = QWidget(self.frame_train_model)
        self.horizontalLayoutWidget_3.setObjectName(u"horizontalLayoutWidget_3")
        self.horizontalLayoutWidget_3.setGeometry(QRect(80, 240, 321, 49))
        self.btn_layout_7 = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.btn_layout_7.setObjectName(u"btn_layout_7")
        self.btn_layout_7.setContentsMargins(0, 0, 0, 0)
        self.frame_save_model = QFrame(self.frame_2)
        self.frame_save_model.setObjectName(u"frame_save_model")
        self.frame_save_model.setGeometry(QRect(60, 160, 521, 301))
        self.frame_save_model.setFrameShape(QFrame.NoFrame)
        self.frame_save_model.setFrameShadow(QFrame.Raised)


        self.frame_save_model.setEnabled(False)
        self.frame_save_model.setVisible(False)


        self.label_13 = QLabel(self.frame_save_model)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(100, 0, 360, 41))
        self.verticalLayoutWidget_4 = QWidget(self.frame_save_model)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(120, 50, 251, 161))
        self.circular_layout_4 = QVBoxLayout(self.verticalLayoutWidget_4)
        self.circular_layout_4.setObjectName(u"circular_layout_4")
        self.circular_layout_4.setContentsMargins(0, 0, 0, 0)
        self.label_14 = QLabel(self.frame_save_model)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(90, 210, 311, 41))
        self.horizontalLayoutWidget_4 = QWidget(self.frame_save_model)
        self.horizontalLayoutWidget_4.setObjectName(u"horizontalLayoutWidget_4")
        self.horizontalLayoutWidget_4.setGeometry(QRect(80, 240, 321, 49))
        self.btn_layout_8 = QHBoxLayout(self.horizontalLayoutWidget_4)
        self.btn_layout_8.setObjectName(u"btn_layout_8")
        self.btn_layout_8.setContentsMargins(0, 0, 0, 0)
        self.label.raise_()
        self.label_2.raise_()
        self.groupBox_1.raise_()
        #self.groupBox_2.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.frame_load_images.raise_()
        self.frame_train_model.raise_()
        self.frame_save_model.raise_()
        self.graphicsView1 = QGraphicsView(self.frame)
        self.graphicsView1.setObjectName(u"graphicsView1")
        self.graphicsView1.setGeometry(QRect(640, 100, 256, 192))
        self.graphicsView1.setFrameShape(QFrame.NoFrame)
        self.graphicsView2 = QGraphicsView(self.frame)
        self.graphicsView2.setObjectName(u"graphicsView2")
        self.graphicsView2.setGeometry(QRect(940, 380, 256, 192))
        self.graphicsView2.setFrameShape(QFrame.NoFrame)
        self.graphicsView3 = QGraphicsView(self.frame)
        self.graphicsView3.setObjectName(u"graphicsView3")
        self.graphicsView3.setGeometry(QRect(640, 380, 256, 192))
        self.graphicsView3.setFrameShape(QFrame.NoFrame)
        self.graphicsView4 = QGraphicsView(self.frame)
        self.graphicsView4.setObjectName(u"graphicsView4")
        self.graphicsView4.setGeometry(QRect(930, 100, 256, 192))
        self.graphicsView4.setFrameShape(QFrame.NoFrame)
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(680, 70, 151, 17))
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(950, 70, 151, 17))
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(680, 350, 151, 17))
        self.label_7 = QLabel(self.frame)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(970, 350, 151, 17))

        self.page_1_layout.addWidget(self.frame)

        self.pages.addWidget(self.page_1)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.page_2_layout = QVBoxLayout(self.page_2)
        self.page_2_layout.setSpacing(5)
        self.page_2_layout.setObjectName(u"page_2_layout")
        self.page_2_layout.setContentsMargins(5, 5, 5, 5)
        self.pages.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.page_3.setStyleSheet(u"QFrame {\n"
"	font-size: 16pt;\n"
"}")
        self.page_3_layout = QVBoxLayout(self.page_3)
        self.page_3_layout.setObjectName(u"page_3_layout")
        self.pages.addWidget(self.page_3)

        self.main_pages_layout.addWidget(self.pages)


        self.retranslateUi(MainPages)

        self.pages.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainPages)
    # setupUi

    def retranslateUi(self, MainPages):
        MainPages.setWindowTitle(QCoreApplication.translate("MainPages", u"Form", None))
        self.label_3.setText(QCoreApplication.translate("MainPages", u"<html><head/><body><p>250 images are required</p></body></html>", None))
        self.label_8.setText(QCoreApplication.translate("MainPages", u"<html><head/><body><p>Drag and Drop or Select images</p></body></html>", None))
        self.label.setText(QCoreApplication.translate("MainPages", u"Select Model", None))
        self.label_2.setText(QCoreApplication.translate("MainPages", u"Select stream", None))
        self.groupBox_1.setTitle("")
        self.groupBox_2.setTitle("")
        self.label_11.setText(QCoreApplication.translate("MainPages", u"<html><head/><body><p>Training started for YOLO5</p></body></html>", None))
        self.label_12.setText(QCoreApplication.translate("MainPages", u"<html><head/><body><p>On 250 images</p></body></html>", None))
        self.label_13.setText(QCoreApplication.translate("MainPages", u"<html><head/><body><p>250 images are required for YOLO5</p></body></html>", None))
        self.label_14.setText(QCoreApplication.translate("MainPages", u"<html><head/><body><p>Drag and Drop or Select images</p></body></html>", None))
        self.label_4.setText(QCoreApplication.translate("MainPages", u"Stream Name A", None))
        self.label_5.setText(QCoreApplication.translate("MainPages", u"Preview Stream", None))
        self.label_6.setText(QCoreApplication.translate("MainPages", u"Preview Stream", None))
        self.label_7.setText(QCoreApplication.translate("MainPages", u"Preview Stream", None))
    # retranslateUi

